image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew


build_script:
<<<<<<< HEAD
  - ./gradlew test --injfo  # запускаем тест, флаг --info позволяет выводить больше информации
=======
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
>>>>>>> 1287d91b38b41e09a9c76d8cf7167e94fad5c0a1
